server:
  servlet:
    context-path: /api
spring:
  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost/demo
    username: root
    password: vng@123
    hikari:
      connection-timeout: 15000
      idle-timeout: 120000
      minimum-idle: 3
      maximum-pool-size: 20
      max-lifetime: 1800000
      pool-name: stg
    prd:
      url: jdbc:mysql://localhost/demo_prd
      username: root
      password: vng@123
      hikari:
        connection-timeout: 15000
        idle-timeout: 120000
        minimum-idle: 3
        maximum-pool-size: 10
        max-lifetime: 1800000
        pool-name: prd
