server:
  servlet:
    context-path: /api
spring:
  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch_size: 50
  datasource:
    hikari:
      connection-timeout: 15000
      idle-timeout: 120000
      minimum-idle: 3
      maximum-pool-size: 30
      max-lifetime: 1800000
    primary:
      url: jdbc:mysql://localhost/demo
      username: root
      password: vng@123
    prd:
      url: jdbc:mysql://localhost/demo_prd
      username: root
      password: vng@123
      hikari:
        connection-timeout: 15000
        idle-timeout: 120000
        minimum-idle: 3
        maximum-pool-size: 10
        max-lifetime: 1800000
